version: '3'

volumes:
  mongo_db:
    external: true

services:
  delo-server:
    build: .
    restart: always
    ports:
      - '8080:8080'
    env_file:
      - ./.env.local
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:4.4
    restart: always
    volumes:
      - mongo_db:/data/db
    ports:
      - '27017:27017'

  redis:
    image: redis
    restart: always
    ports:
      - '6379:6379'